apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: loom-server
  name: loom-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: loom-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: loom-server
    spec:
      containers:
      - image: gcr.io/linnarsson-lab/loom-server:v1
        imagePullPolicy: Always
        name: loom-server
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30